apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/trihuynh-98/tracing-stack.git"
    targetRevision: main
    path: tracing-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true