apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/<YOUR_GITHUB_USER>/tracing-stack.git"
    targetRevision: main
    path: base/grafana
    helm:
      chart: grafana
      repoURL: "https://grafana.github.io/helm-charts"
      version: "9.2.0"  # example version
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
