apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/<YOUR_GITHUB_USER>/tracing-stack.git"
    targetRevision: main
    path: base/otel-collector
    helm:
      chart: opentelemetry-collector
      repoURL: "https://open-telemetry.github.io/opentelemetry-helm-charts"
      version: "0.70.0"  # pick a stable version
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tracing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
